
exports.city = require('./city.js')
exports.coordinate = require('./coordinate.js')
exports.country = require('./country.js')
exports.credentials = require('./credentials.js')
exports.service = require('./service.js')
exports.user_address = require('./user_address.js')
exports.user_type = require('./user_type.js')
exports.users = require('./users.js')
exports.users_has_address = require('./users_has_address.js')
exports.users_has_credentials = require('./users_has_credentials.js')